AUTHORITY_TO_TOWN = {
    "ATTLEBOROUGH": "ATTLEBORO",
    "MANCHESTER": "MANCHESTER-BY-THE-SEA",
    "N. ATTLEBOROUGH": "NORTH ATTLEBOROUGH",
}

EXCLUDE_AUTHORITIES = [
    "CRIMINAL HISTORY SYSTEMS BOARD",
    "MASS STATE POLICE",
]
